Repository project-origin/registry, pull requests merged in 2024-04, with the labels that each got.

#329 Fix publish missing secret
  .github/workflows/release-published.yaml
Labels: ci

#335 Add required `serviceName`
  charts/project-origin-registry/templates/registry-deployment.yaml
Labels: enhancement

#362 Update doc
  README.md
  doc/components/block_finalizer.md
  doc/contribute/create_release.md
  doc/contribute/toc.yml
  doc/diagrams/block_finalizer.drawio.svg
  doc/diagrams/container.drawio.svg
  doc/diagrams/registry_service.component.drawio.svg
  doc/diagrams/system_diagram.drawio.svg
  doc/docfx.json
  doc/index.md
  doc/logo.svg
  doc/quickstart.md
  doc/registry_service.md
  doc/registry_system.md
  doc/toc.yml
Labels: documentation
